name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Building the website
        run: |
          npm i
          npm run deploy
